### PR TITLE
Add takedowns, better package structure, optionally disable presence

### PR DESCRIPTION
**Pull request by philmcmahon**
This PR overhauls the status bar logic to make it nice and typed. It adds a server side check for the status of an explainer which can optionally hit the content api to determine if an explainer is live or not. This is only used on page load - otherwise status checking is done client side, using some evil evil state to store whether or not an item has been taken down.

It also makes it possible to disable presence via a config property.

### CODE REVIEW

**Comment by philmcmahon** [comment]
Depends on https://github.com/guardian/content-api/pull/1697

**Comment by shtukas** [comment]
Deployed to CODE

**Comment by shtukas** [comment]
Note: I have noticed this morning that there is a little problem with the Commissioning Desk selection, and made a note to myself to fix it, but there is also a "Fix desks dropdown" item in your list of changes. I don't know if you meant to fix the same thing, but for the moment it is still broken in your change. I will +1 anyway.

**Comment by shtukas** [comment]
:+1:

**Pull request merged**
