### PR TITLE
Enabling ordered lists in the editor

### PR DESCRIPTION
**Pull request by shtukas**

### CODE REVIEW

**Comment by shtukas** [comment]
screen shot 2016-08-31 at 11 19 48

**Comment by shaundillon** [comment]
@shtukas - It'd be good if at some point we could add icons for these instead:
picture 120

**Comment by shtukas** [comment]
+1 for icons!

**Comment by philmcmahon** [comment]
Yep - icons would be great - either in this PR or another one. Could you make the text 'Bullet list' and 'Numbered list'

**Comment by shtukas** [comment]
I added "Use icons instead of text for editor styling functionalities" is the list of stuff to do, so we can merge this PR without them.

**Comment by philmcmahon** [comment]
Sorry, make that 'Bulleted list'

**Comment by shtukas** [comment]
> make that 'Bulleted list'

Done.

screen shot 2016-08-31 at 13 19 43

**Comment by shtukas** [comment]
screen shot 2016-08-31 at 14 29 26

**Comment by shaundillon** [comment]
👍

**Pull request merged**
