### PR TITLE
Another modernisation branch

### PR DESCRIPTION
**Pull request by sihil**
This time:
 - Switch to riff-raff.yaml
 - Switch to debian packages
 - Switch to AMIgo AMI with auto updating

### CODE REVIEW

**Comment by sihil** [comment]
Working on CODE

**Comment by sihil** [comment]
[Explain Maker: Update AMI / Riff-Raff](https://trello.com/c/NB6V9Owr/186-explain-maker-update-ami-riff-raff)

**Comment by shaundillon** [comment]
I can't remember what the outcome was, but I believe there was talk of keeping all of the cf files in one place over at https://github.com/guardian/editorial-tools-platform

**Comment by sihil** [comment]
Agreed - but not as part of this (especially since this is going to be disposed of shortly). My priority is to get everything onto recent AMIs.

**Comment by shaundillon** [comment]
@sihil - Fair point, aside from that then, LGTM

**Review by shaundillon — APPROVED** [review]

**Pull request merged**
