### PR TITLE
Setting the correct editor menus items

### PR DESCRIPTION
**Pull request by shtukas**
In this commit we remove the un-necessary menu items that come with the
default settings of Tinymce and only keep those needed for basic rich
text editing.

### CODE REVIEW

**Comment by shtukas** [comment]
Before:

before

**Comment by shtukas** [comment]
After:

after

**Comment by philmcmahon** [comment]
Looking good! Could you also remove the alignment buttons and maybe add an underline?

**Comment by philmcmahon** [comment]
(by alignment I mean the ones in the middle - left/centered/justify

**Comment by shtukas** [comment]
> maybe add an underline?

Just noticed that underline was already there and comes as Format -> Inline -> Underline

**Comment by shtukas** [comment]
picture 1

**Comment by shtukas** [comment]
- Brought the height of the editor back to 300px (as it had always been too high).
- Simplified the toolbar.
  We now have bold, italic, and underline in the toolbar and more advanced
  formatting options in the "Formats" menu.

**Comment by philmcmahon** [comment]
Sorry, but we still need bullet points!

**Comment by shtukas** [comment]
Done :)

picture 2

**Comment by philmcmahon** [comment]
👍

**Pull request merged**
