### PR TITLE
Introducing a new toolbar

### PR DESCRIPTION
**Pull request by shtukas**
In this commit: a new toolbar with:
1. Left hand side place holders for the (future) logo and additional icon.
2. The "Back to dashboard" to dashboard thing that Phil likes very much ;)
   Only displays on the Editor page.
   Thanks Shaun for it.
3. Right hand side dislay of the user identity
4. Right hand side [Create New] button.
   Only displays on the Dashboard

### CODE REVIEW

**Comment by shtukas** [comment]
picture 1

**Comment by shtukas** [comment]
picture 2

**Comment by shtukas** [comment]
nb: Not yet done: Move the status bar to the tool bar

**Comment by philmcmahon** [comment]
Some things:
- Logo issues in firefox
- Add logo ready for replacement
- Back to dashboard font
- Name rather than email - check how quiz builder is doing it
- Use full name rather than email?

**Comment by shtukas** [comment]
> Logo issues in firefox
> Add logo ready for replacement
> Back to dashboard font

Done.

> Use full name rather than email?

Checking in CODE that it is working fine.

**Comment by shtukas** [comment]
> Checking in CODE that it is working fine.

Confirming working fine on CODE.

picture 1

**Comment by philmcmahon** [comment]
👍

**Pull request merged**
