### PR TITLE
Activating Presence on the Explainer Editor

### PR DESCRIPTION
**Pull request by shtukas**

### CODE REVIEW

**Comment by shtukas** [comment]
Below when myself and Shaun were looking at the same document.

screen shot 2016-08-23 at 15 45 42

**Comment by shaundillon** [comment]
👍

**Comment by shtukas** [comment]
I have just updated the CODE and PROD config files with their respective presence URLs.

**Comment by shtukas** [comment]
Deployed and tested on CODE.

**Pull request merged**
